[server]
headless = false
enableCORS = false
enableXsrfProtection = false
address = "localhost"
port = 8501

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#2c5530"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#e8f5e8"
textColor = "#2c5530"
font = "sans serif"
